sudo: required

services:
  - docker

env:
  global:
    - DOCKER_VERSION=17.06.0~ce-0~ubuntu

before_install:
  - apt-cache madison docker-ce
  - >-
    sudo apt-get -o Dpkg::Options::='--force-confnew' install -y --force-yes
    docker-ce=${DOCKER_VERSION}
  - docker version
  - docker info
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -y
  - >-
    sudo apt-get install -y
    bats
    ldap-utils

script:
  - make test
